import { Inter } from "next/font/google";
import { MantineWrapper } from "../libs/MantineWrapper";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Lecture14",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
        <title>{metadata.title}</title>
        <meta name="description" content={metadata.description} />
        <link rel="icon" href="/favicon.ico" />
      </head>
      <body className={inter.className}>
        <MantineWrapper>
          {children}
        </MantineWrapper>
      </body>
    </html>
  );
}
